subcat_link_list = [
    {'url': 'https://www.zalando.co.uk/womens-shoes-classic-ankle-boots/', 'gender': 'female',
     'category': 'Boots', 'subcategory': 'Classic Ankle Boots'},
    {'url': 'https://www.zalando.co.uk/cowboy-biker-ankle-boots/', 'gender': 'female', 'category': 'Boots',
     'subcategory': 'Cowboy & Biker Ankle Boots'},
    {'url': 'https://www.zalando.co.uk/ankle-high-boots/', 'gender': 'female', 'category': 'Boots',
     'subcategory': 'Heeled Ankle Boots'},
    {'url': 'https://www.zalando.co.uk/lace-up-ankle-boots/', 'gender': 'female', 'category': 'Boots',
     'subcategory': 'Lace up Ankle Boots'},
    {'url': 'https://www.zalando.co.uk/platform-ankle-boots/', 'gender': 'female', 'category': 'Boots',
     'subcategory': 'Platform Ankle Boots'},
    {'url': 'https://www.zalando.co.uk/wedge-ankle-boots/', 'gender': 'female', 'category': 'Boots',
     'subcategory': 'Wedge Ankle Boots'},
    {'url': 'https://www.zalando.co.uk/ankle-cuff-ballet-pumps/', 'gender': 'female', 'category': 'Ballet Pumps',
     'subcategory': 'Ankle Cuff Ballet Pumps'},
    {'url': 'https://www.zalando.co.uk/ankle-strap-ballet-pumps/', 'gender': 'female', 'category': 'Ballet Pumps',
     'subcategory': 'Ankle Strap Ballet Pumps'},
    {'url': 'https://www.zalando.co.uk/classic-ballet-pumps/', 'gender': 'female', 'category': 'Ballet Pumps',
     'subcategory': 'Classic Ballet Pumps'},
    {'url': 'https://www.zalando.co.uk/foldable-ballet-pumps/', 'gender': 'female', 'category': 'Ballet Pumps',
     'subcategory': 'Foldable Ballet Pumps'},
    {'url': 'https://www.zalando.co.uk/peep-toe-ballet-pumps/', 'gender': 'female', 'category': 'Ballet Pumps',
     'subcategory': 'Peep-Toe Ballet Pumps'},
    {'url': 'https://www.zalando.co.uk/classic-boots/', 'gender': 'female', 'category': 'Boots',
     'subcategory': 'Classic Boots'},
    {'url': 'https://www.zalando.co.uk/cowboy-boots-biker-boots/', 'gender': 'female', 'category': 'Boots',
     'subcategory': 'Cowboy & Biker Boots'},
    {'url': 'https://www.zalando.co.uk/boots/', 'gender': 'female', 'category': 'Boots',
     'subcategory': 'Heeled Boots'},
    {'url': 'https://www.zalando.co.uk/lace-up-boots/', 'gender': 'female', 'category': 'Boots',
     'subcategory': 'Lace up Boots'},
    {'url': 'https://www.zalando.co.uk/platform-boots/', 'gender': 'female', 'category': 'Boots',
     'subcategory': 'Platform Boots'},
    {'url': 'https://www.zalando.co.uk/snow-boots/', 'gender': 'female', 'category': 'Boots',
     'subcategory': 'Snow Boots'},
    {'url': 'https://www.zalando.co.uk/womens-shoes-thigh-highs/', 'gender': 'female', 'category': 'Boots',
     'subcategory': 'Thigh high Boots'},
    {'url': 'https://www.zalando.co.uk/wedge-boots/', 'gender': 'female', 'category': 'Boots',
     'subcategory': 'Wedge Boots'},
    {'url': 'https://www.zalando.co.uk/womens-shoes-wellies/', 'gender': 'female', 'category': 'Boots',
     'subcategory': 'Wellies'},
    {'url': 'https://www.zalando.co.uk/boat-shoes/', 'gender': 'female', 'category': 'Flats & Lace-Ups',
     'subcategory': 'Boat Shoes'},
    {'url': 'https://www.zalando.co.uk/brogues-lace-ups/', 'gender': 'female', 'category': 'Flats & Lace-Ups',
     'subcategory': 'Brogues & Lace-Ups'},
    {'url': 'https://www.zalando.co.uk/womens-shoes-espadrilles/', 'gender': 'female', 'category': 'Flats & Lace-Ups',
     'subcategory': 'Espadrilles'},
    {'url': 'https://www.zalando.co.uk/womens-shoes-loafers/', 'gender': 'female', 'category': 'Flats & Lace-Ups',
     'subcategory': 'Loafers'},
    {'url': 'https://www.zalando.co.uk/womens-shoes-moccasins/', 'gender': 'female', 'category': 'Flats & Lace-Ups',
     'subcategory': 'Moccasins'},
    {'url': 'https://www.zalando.co.uk/sporty-lace-ups/', 'gender': 'female', 'category': 'Flats & Lace-Ups',
     'subcategory': 'Sporty Lace-Ups'},
    {'url': 'https://www.zalando.co.uk/womens-shoes-beach-shoes/', 'gender': 'female', 'category': 'Flip Flops',
     'subcategory': 'Beach Shoes'},
    {'url': 'https://www.zalando.co.uk/flip-flops/', 'gender': 'female', 'category': 'Flip Flops',
     'subcategory': 'Flip Flops'},
    {'url': 'https://www.zalando.co.uk/classic-heels/', 'gender': 'female', 'category': 'Heels',
     'subcategory': 'Classic Heels'},
    {'url': 'https://www.zalando.co.uk/womens-shoes-bridal-shoes/', 'gender': 'female', 'category': 'Heels',
     'subcategory': 'Bridal Shoes'},
    {'url': 'https://www.zalando.co.uk/womens-shoes-high-heels/', 'gender': 'female', 'category': 'Heels',
     'subcategory': 'High Heels'},
    {'url': 'https://www.zalando.co.uk/lace-up-heels/', 'gender': 'female', 'category': 'Heels',
     'subcategory': 'Lace-up Heels'},
    {'url': 'https://www.zalando.co.uk/womens-shoes-peep-toes/', 'gender': 'female', 'category': 'Heels',
     'subcategory': 'Peep Toes'},
    {'url': 'https://www.zalando.co.uk/platform-heels/', 'gender': 'female', 'category': 'Heels',
     'subcategory': 'Platform Heels'},
    {'url': 'https://www.zalando.co.uk/wedges/', 'gender': 'female', 'category': 'Heels',
     'subcategory': 'Wedges'},
    {'url': 'https://www.zalando.co.uk/premium-womens-heels/', 'gender': 'female', 'category': 'Heels',
     'subcategory': 'Designer Heels'},
    {'url': 'https://www.zalando.co.uk/womens-shoes-clogs/', 'gender': 'female', 'category': 'Clogs',
     'subcategory': 'Clogs'},
    {'url': 'https://www.zalando.co.uk/womens-shoes-mules/', 'gender': 'female', 'category': 'Mules',
     'subcategory': 'Mules'},
    {'url': 'https://www.zalando.co.uk/womens-hiking-boots/', 'gender': 'female',
     'category': 'Hiking & Hillwalking Shoes', 'subcategory': 'Hiking Boots'},
    {'url': 'https://www.zalando.co.uk/womens-walking-boots/', 'gender': 'female',
     'category': 'Hiking & Hillwalking Shoes', 'subcategory': 'Walking Boots'},
    {'url': 'https://www.zalando.co.uk/womens-mountain-boots/', 'gender': 'female',
     'category': 'Hiking & Hillwalking Shoes', 'subcategory': 'Mountain Boots'},
    {'url': 'https://www.zalando.co.uk/womens-sports-sandals/', 'gender': 'female',
     'category': 'Hiking & Hillwalking Shoes', 'subcategory': 'Sandals'},
    {'url': 'https://www.zalando.co.uk/ankle-cuff-sandals/', 'gender': 'female', 'category': 'Sandals',
     'subcategory': 'Ankle Cuff Sandals'},
    {'url': 'https://www.zalando.co.uk/flip-flops-thong-sandals/', 'gender': 'female', 'category': 'Sandals',
     'subcategory': 'Flip Flops & Thong Sandals'},
    {'url': 'https://www.zalando.co.uk/sandals/', 'gender': 'female', 'category': 'Sandals',
     'subcategory': 'Heeled Sandals'},
    {'url': 'https://www.zalando.co.uk/platform-sandals/', 'gender': 'female', 'category': 'Sandals',
     'subcategory': 'Platform Sandals'},
    {'url': 'https://www.zalando.co.uk/strappy-sandals/', 'gender': 'female', 'category': 'Sandals',
     'subcategory': 'Strappy Sandals'},
    {'url': 'https://www.zalando.co.uk/wedge-sandals/', 'gender': 'female', 'category': 'Sandals',
     'subcategory': 'Wedge Sandals'},
    {'url': 'https://www.zalando.co.uk/womens-shoes-slippers/', 'gender': 'female', 'category': 'Slippers',
     'subcategory': 'Slippers'},
    {'url': 'https://www.zalando.co.uk/womens-running-shoes/', 'gender': 'female', 'category': 'Sports Shoes',
     'subcategory': 'Running Shoes'},
    {'url': 'https://www.zalando.co.uk/womens-cushioned-running-shoes/', 'gender': 'female', 'category': 'Sports Shoes',
     'subcategory': 'Cushioned'},
    {'url': 'https://www.zalando.co.uk/womens-stability-running-shoes/', 'gender': 'female', 'category': 'Sports Shoes',
     'subcategory': 'Stability'},
    {'url': 'zalando.co.uk/womens-lightweight-running-shoes/', 'gender': 'female', 'category': 'Sports Shoes',
     'subcategory': 'Lightweight'},
    {'url': 'https://www.zalando.co.uk/womens-natural-running/', 'gender': 'female', 'category': 'Sports Shoes',
     'subcategory': 'Natural Running'},
    {'url': 'https://www.zalando.co.uk/womens-trail-running-shoes/', 'gender': 'female', 'category': 'Sports Shoes',
     'subcategory': 'Trail'},
    {'url': 'https://www.zalando.co.uk/womens-walking-shoes/', 'gender': 'female', 'category': 'Sports Shoes',
     'subcategory': 'Walking'},
    {'url': 'https://www.zalando.co.uk/womens-running-shoes-spikes/', 'gender': 'female', 'category': 'Sports Shoes',
     'subcategory': 'Spikes'},
    {'url': 'https://www.zalando.co.uk/womens-football-boots/', 'gender': 'female', 'category': 'Sports Shoes',
     'subcategory': 'Football Boots'},
    {'url': 'https://www.zalando.co.uk/womens-basketball-shoes/', 'gender': 'female', 'category': 'Sports Shoes',
     'subcategory': 'Basketball Shoes'},
    {'url': 'https://www.zalando.co.uk/womens-tennis-shoes/', 'gender': 'female', 'category': 'Sports Shoes',
     'subcategory': 'Tennis Shoes'},
    {'url': 'https://www.zalando.co.uk/womens-golf-shoes/', 'gender': 'female', 'category': 'Sports Shoes',
     'subcategory': 'Golf shoes'},
    {'url': 'https://www.zalando.co.uk/womens-trainers-fitness-shoes/', 'gender': 'female', 'category': 'Sports Shoes',
     'subcategory': 'Trainers Shoes'},
    {'url': 'https://www.zalando.co.uk/womens-beach-shoes/', 'gender': 'female', 'category': 'Sports Shoes',
     'subcategory': 'Beach Shoes'},
    {'url': 'https://www.zalando.co.uk/womens-trainers-sports/', 'gender': 'female', 'category': 'Sports Shoes',
     'subcategory': 'Trainers'},
    {'url': 'https://www.zalando.co.uk/womens-cycling-shoes/', 'gender': 'female', 'category': 'Sports Shoes',
     'subcategory': 'Cycling Shoes'},
    {'url': 'https://www.zalando.co.uk/womens-shoes-trainers/', 'gender': 'female', 'category': 'Trainers',
     'subcategory': 'Trainers'},
    {'url': 'https://www.zalando.co.uk/mens-shoes-ankle-boots/', 'gender': 'male', 'category': 'Boots',
     'subcategory': 'Ankle Boots'},
    {'url': 'https://www.zalando.co.uk/mens-shoes-winter-boots/', 'gender': 'male', 'category': 'Boots',
     'subcategory': 'Winter Boots'},
    {'url': 'https://www.zalando.co.uk/mens-shoes-lace-up-boots/', 'gender': 'male', 'category': 'Boots',
     'subcategory': 'Lace-up Boots'},
    {'url': 'https://www.zalando.co.uk/mens-shoes-wellies/', 'gender': 'male', 'category': 'Boots',
     'subcategory': 'Wellies'},
    {'url': 'https://www.zalando.co.uk/mens-shoes-cowboy-biker-boots/', 'gender': 'male', 'category': 'Boots',
     'subcategory': 'Cowboy & Biker Boots'},
    {'url': 'https://www.zalando.co.uk/mens-shoes-brogues-lace-ups/', 'gender': 'male', 'category': 'Casual Shoes',
     'subcategory': 'Brogues'},
    {'url': 'https://www.zalando.co.uk/mens-shoes-loafers/', 'gender': 'male', 'category': 'Casual Shoes',
     'subcategory': 'Slip Ons'},
    {'url': 'https://www.zalando.co.uk/mens-shoes-boat-shoes/', 'gender': 'male', 'category': 'Casual Shoes',
     'subcategory': 'Boat Shoes'},
    {'url': 'https://www.zalando.co.uk/mens-shoes-moccasins/', 'gender': 'male', 'category': 'Casual Shoes',
     'subcategory': 'Moccasins'},
    {'url': 'https://www.zalando.co.uk/mens-shoes-sporty-lace-ups/', 'gender': 'male', 'category': 'Casual Shoes',
     'subcategory': 'Sporty Lace Ups'},
    {'url': 'https://www.zalando.co.uk/mens-shoes-espadrilles/', 'gender': 'male', 'category': 'Casual Shoes',
     'subcategory': 'Espadrilles'},
    {'url': 'https://www.zalando.co.uk/mens-shoes-derbies-business-shoes/', 'gender': 'male',
     'category': 'Formal Shoes', 'subcategory': 'Derbies & Oxfords'},
    {'url': 'https://www.zalando.co.uk/mens-shoes-business-shoes-loafers/', 'gender': 'male',
     'category': 'Formal Shoes', 'subcategory': 'Loafers'},
    {'url': 'https://www.zalando.co.uk/mens-outdoor-shoes/', 'gender': 'male', 'category': 'Hiking & Hillwalking Shoes',
     'subcategory': 'Hiking Boots'},
    {'url': 'https://www.zalando.co.uk/mens-shoes-flip-flops/', 'gender': 'male', 'category': 'Sandals',
     'subcategory': 'Flip Flops'},
    {'url': 'https://www.zalando.co.uk/mens-shoes-casual-sandals/', 'gender': 'male', 'category': 'Sandals',
     'subcategory': 'Casual Sandals'},
    {'url': 'https://www.zalando.co.uk/mens-shoes-beach-shoes/', 'gender': 'male', 'category': 'Sandals',
     'subcategory': 'Beach Shoes'},
    {'url': 'https://www.zalando.co.uk/mens-shoes-slippers/', 'gender': 'male', 'category': 'Slippers',
     'subcategory': 'Slippers'},
    {'url': 'https://www.zalando.co.uk/mens-shoes-slides/', 'gender': 'male', 'category': 'Slides & Clogs',
     'subcategory': 'Sliders'},
    {'url': 'https://www.zalando.co.uk/mens-shoes-clogs/', 'gender': 'male', 'category': 'Slides & Clogs',
     'subcategory': 'Clogs'},
    {'url': 'https://www.zalando.co.uk/mens-sports-shoes/', 'gender': 'male', 'category': 'Sports Shoes',
     'subcategory': 'Sport'},
    {'url': 'https://www.zalando.co.uk/mens-shoes-trainers/', 'gender': 'male', 'category': 'Trainers',
     'subcategory': 'Trainers'}]

















