Season_list = ['spring', 'summer', 'autumn', 'winter', 'festive']  # Summer, Winter, Spring, Autumn....
Category1_list = ['stitched', 'unstitched', 'pret', 'ready to wear', 'formal', 'basics']
Dress_Type_list = ['sweatshirt', 'cardigan', 'skirt', 'prince coat', 'shorts', 'waistcoat', 'Shirt', 'Shalwar', 'Dupatta',
                   '2pc','2 pcs', '3pc', '3-pc', '2-pc', '2-piece', '3-piece', 'jogging-suit', 'night-suit', 'blazer',
                   't-shirt', 'tshirt', 't shirt', 'jacket', 'full-dress', 'lower-dress', 'upper-dress', 'shirt',
                   'pant', 'coat', 'jacket', 'trouser', 'sweater', 'stole'
                                                                   'shalwar', 'tights', 'kurta', 'pajama', 'blouse',
                   'full', 'suit', 'bottom', 'dupatta', 'fusion', 'contemporary', 'traditional', 'kurta', 'top']
Fabric_list = ['georgette', 'tweed', 'wool', 'linen', 'Cambric', 'cambric', 'Chiffon', 'chiffon', 'denim', 'Denim',
               'Velvet', 'velvet', 'silk', 'Silk', 'cotton', 'Cotton',
               'lawn', 'Lawn', 'Jacquard', 'jacquard', 'net', 'polyester']
Design_Pattern_List = ['embroidered']
Region_list = ['ethnic', 'eastern', 'western', 'fusion', 'contemporary', 'traditional']
Male_Gender_list = ['man', 'men', 'mens', 'mans', 'gents', 'gentleman', 'gentlemen']
Female_Gender_List = ['women', 'woman', 'womens', 'womans', 'ladies', 'mom']
Boys_Gender_List = ['boys', 'boy']
Girls_Gender_List = ['girl', 'girls']
Kids_Gender_List = ['kids', 'kid']
others = ['ready-to-wear', 'separates']
events_list = ['eid', 'new', 'festive']
# aywa london sanam chaudhri sania maskatiya
exclude_brand_list = ['Sana Safinaz', 'Khaadi', 'Baroque', 'Maria.B', 'Bonanza', 'Zeen', 'Oaks', 'Generation',
                      'Mausummery', 'Zara Shahjahan', 'Mahgul', 'Forecast', 'Nishat Linen', 'Gul Ahmed', 'Al karam',
                      'Almirah', 'Chen one', 'Cherry House', 'Number3', 'Ismail Farid Western', 'Ismail Farid Eastern',
                      'charcoal', 'Outfitters', 'Engine', 'Uniworth', 'Royal tag', 'Monark', 'sana safinaz', 'khaadi',
                      'baroque', 'maria.b', 'bonanza', 'zeen', 'oaks', 'generation', 'mausummery', 'zara shahjahan',
                      'mahgul', 'forecast', 'nishat linen', 'gul ahmed', 'al karam', 'almirah', 'chen one',
                      'cherry house', 'number3', 'ismail farid western', 'ismail farid eastern', 'outfitters', 'engine',
                      'uniworth', 'royal tag', 'monark', 'Sana-Safinaz', 'Zara-Shahjahan', 'Nishat-Linen', 'Gul-Ahmed',
                      'Al-karam', 'Chen-one', 'Cherry-House', 'Ismail-Farid-Western', 'Ismail-Farid-Eastern',
                      'Royal-tag', 'sana-safinaz', 'zara-shahjahan', 'nishat-linen', 'gul-ahmed', 'al-karam',
                      'chen-one', 'cherry-house', 'ismail-farid-western', 'ismail-farid-eastern', 'royal-tag',
                      'SanaSafinaz', 'ZaraShahjahan', 'NishatLinen', 'GulAhmed', 'Alkaram', 'Chenone', 'CherryHouse',
                      'IsmailFaridWestern', 'IsmailFaridEastern', 'Royaltag', 'sanasafinaz', 'zarashahjahan',
                      'nishatlinen', 'gulahmed', 'alkaram', 'chenone', 'cherryhouse', 'ismailfaridwestern',
                      'ismailfarideastern', 'royaltag', 'nilofer-shahid', 'saira-rizwan', 'sania-maskatiya',
                      'natasha-kamal', 'maria-b', 'rani-emaan', 'designs-by-amina', 'bonanza-satrangi', 'sifona',
                      'white-shalwar', 'mens-kurta-brown', 'mens-kurta-grey', 'mochi-cordwainers', 'shehrnaz',
                      'yasmin-zaman', 'mehr', 'ego', 'insam', 'pinktree', 'maheen-ghani-taseer',
                      'wide-leg-georgette-trouser', 'sanam-chaudhri', 'colour-blocked-georgette-pants', 'tena-durrani',
                      'shamaeel', 'gold-lame-pants', 'deepak-perwani', 'khas-stores', 'macramé', 'najwa',
                      'dilaawaiz-by-sahar', 'faiza-samee', 'hussain-rehar', 'misha-lakhani', 'asim-jofa',
                      'maheen-karim', 'huma-adnan', 'raishma', 'amroshé', 'bonanza|satrangi', 'tarzz',
                      'maheen-karim-by-z.s.-textiles', 'zunn-fashion', 'macrame', 'fnkasia', 'kuli-jumé',
                      'samaira-ghani', 'macrame-–-black-&-white-print-wonder-orchid',
                      'misha-lakhani-hand-woven-mardana', 'misha-lakhani-printed-mardana',
                      'misha-lakhani-light-pink-alisha', 'misha-lakhani-coral-pink-nina-top',
                      'misha-lakhani-light-pink-maddy-top', 'saleha-kashif', 'nadya-shah', 'kiyaraa', 'adeela-salehjee',
                      'maliha-kamal', 'kiyaara', 'mehreen-noorani', 'maheen-taseer', 'popistan', 'aywa-london',
                      'seher-tareen', 'basit-sipra', 'ali-xeeshan', 'nilofershahid', 'sairarizwan', 'saniamaskatiya',
                      'natashakamal', 'mariab', 'raniemaan', 'designsbyamina', 'bonanzasatrangi', 'whiteshalwar',
                      'menskurtabrown', 'menskurtagrey', 'mochicordwainers', 'yasminzaman', 'maheenghanitaseer',
                      'wideleggeorgettetrouser', 'sanamchaudhri', 'colourblockedgeorgettepants', 'tenadurrani',
                      'goldlamepants', 'deepakperwani', 'khasstores', 'dilaawaizbysahar', 'faizasamee', 'hussainrehar',
                      'mishalakhani', 'asimjofa', 'maheenkarim', 'humaadnan', 'maheenkarimbyz.s.textiles',
                      'zunnfashion', 'kulijumé', 'samairaghani', 'macrame–black&whiteprintwonderorchid',
                      'mishalakhanihandwovenmardana', 'mishalakhaniprintedmardana', 'mishalakhanilightpinkalisha',
                      'mishalakhanicoralpinkninatop', 'mishalakhanilightpinkmaddytop', 'salehakashif', 'nadyashah',
                      'adeelasalehjee', 'malihakamal', 'mehreennoorani', 'maheentaseer', 'aywalondon', 'sehertareen',
                      'basitsipra', 'alixeeshan', 'nilofer shahid', 'saira rizwan', 'sania maskatiya', 'natasha kamal',
                      'maria b', 'rani emaan', 'designs by amina', 'bonanza satrangi', 'white shalwar',
                      'mens kurta brown', 'mens kurta grey', 'mochi cordwainers', 'yasmin zaman', 'maheen ghani taseer',
                      'wide leg georgette trouser', 'sanam chaudhri', 'colour blocked georgette pants', 'tena durrani',
                      'gold lame pants', 'deepak perwani', 'khas stores', 'dilaawaiz by sahar', 'faiza samee',
                      'hussain rehar', 'misha lakhani', 'asim jofa', 'maheen karim', 'huma adnan',
                      'maheen karim by z.s. textiles', 'zunn fashion', 'kuli jumé', 'samaira ghani',
                      'macrame – black & white print wonder orchid', 'misha lakhani hand woven mardana',
                      'misha lakhani printed mardana', 'misha lakhani light pink alisha',
                      'misha lakhani coral pink nina top', 'misha lakhani light pink maddy top', 'saleha kashif',
                      'nadya shah', 'adeela salehjee', 'maliha kamal', 'mehreen noorani', 'maheen taseer',
                      'aywa london', 'seher tareen', 'basit sipra', 'ali xeeshan']
target_data_keywords = events_list + others + Season_list + Category1_list + Dress_Type_list + Fabric_list + Region_list + Male_Gender_list + Female_Gender_List + Boys_Gender_List + Girls_Gender_List + Kids_Gender_List
exclusion_list = ['glasses', 'cufflinks', 'contacts', 'sales', 'checkout', 'login', 'jewellery', 'perfume', 'bedsheet',
                  'sandal', 'bag', 'jogger', 'joggers', 'sock', 'socks', 'foot-wear', 'belt', 'cushion', 'shoes',
                  'hand-bag', '.jpg', '#', '#store.menu', 'add-to-cart', 'blog', 'history', '/product-tag/bottom/',
                  '#quickViewModal', 'javascript', 'wishlist', 'kids', '.pdf', 'catalog', 'fragrances', 'sheets', 'bed',
                  'sunglasses', 'accessories', 'footwear', 'floor runners', 'pocket squares', 'pillow', 'bedding',
                  'jewelry', 'jewellery', 'home', 'heels', 'handbags', 'clutches', 'wallets', 'towel', 'bags', 'card']
# 'polo',


color_List = ['absolute zero', 'acid green', 'aero', 'aero blue', 'african violet', 'air superiority blue', 'alabaster',
              'alice blue', 'alloy orange', 'almond', 'amaranth', 'amaranth deep purple', 'amaranth pink',
              'amaranth purple',
              'amaranth red', 'amazon', 'amber', 'amber (sae/ece)', 'amethyst', 'android green', 'antique brass',
              'antique bronze', 'antique fuchsia', 'antique ruby', 'antique white', 'ao (english)', 'apple green',
              'apricot', 'aqua', 'aquamarine', 'arctic lime', 'army green', 'artichoke', 'arylide yellow', 'ash grey',
              'asparagus', 'atomic tangerine', 'auburn', 'aureolin', 'avocado', 'azure', 'azure (x11/web color)',
              "b'dazzled blue", 'baby blue', 'baby blue eyes', 'baby pink', 'baby powder', 'baker-miller pink',
              'ball blue', 'banana mania', 'banana yellow', 'bangladesh green', 'barbie pink', 'barn red',
              'battery charged blue', 'battleship grey', 'bayside', 'bazaar', 'beau blue', 'begonia', 'beaver',
              'beer', 'beige', 'big dip ruby', 'big foot feet', 'bisque', 'bistre', 'bistre brown', 'bitter lemon',
              'bitter lime', 'bittersweet', 'bittersweet shimmer', 'black', 'black bean', 'black chocolate',
              'black coffee', 'black coral', 'black leather jacket', 'black olive', 'blackberry', 'black shadows',
              'blanched almond', 'blast-off bronze', 'bleu de france', 'blizzard blue', 'blond', 'blood',
              'blood orange',
              'blood red', 'blood (animal)', 'blood (organ)', 'blue', 'blue (crayola)', 'blue (munsell)', 'blue (ncs)',
              'blue (pantone)', 'blue (pigment)', 'blue (ryb)', 'blue bell', 'blue bolt', 'blue cola', 'blue-gray',
              'blue-green', 'blue-green (color wheel)', 'blue jeans', 'blue lagoon', 'blue-magenta violet',
              'blue raspberry', 'blue sapphire', 'blue-violet', 'blue-violet (crayola)', 'blue-violet (color wheel)',
              'blue yonder', 'blueberry', 'bluebonnet', 'blush', 'bole', 'bondi blue', 'bone', 'booger buster',
              'boston university red', 'bottle green', 'boysenberry', 'brandeis blue', 'brandy', 'brave orange',
              'brick red', 'bright cerulean', 'bright gray', 'bright green', 'briquette', 'bright lavender',
              'bright lilac', 'bright maroon', 'bright navy blue', 'bright pink', 'bright turquoise', 'bright ube',
              'bright yellow (crayola)', 'brilliant azure', 'brilliant lavender', 'brilliant rose', 'brink pink',
              'british racing green', 'bronze', 'bronze', 'bronze (metallic)', 'bronze yellow', 'brown',
              'brown (crayola)', 'brown (traditional)', 'brown (web)', 'brown-nose', 'brown sugar',
              'brunswick green', 'bubble gum', 'bubbles', 'bud green', 'buff', 'bulgarian rose',
              'burgundy', 'burlywood', 'burnished brown', 'burnt orange', 'burnt sienna', 'burnt umber',
              'button blue', 'byzantine', 'byzantium', 'cadet', 'cadet blue', 'cadet blue (crayola)',
              'cadet grey', 'cadmium blue', 'cadmium green', 'cadmium orange', 'cadmium purple', 'cadmium red',
              'cadmium yellow', 'cadmium violet', 'caf au lait', 'caf noir', 'cal poly pomona green', 'calamansi',
              'cambridge blue', 'camel', 'cameo pink', 'camouflage green', 'canary', 'canary yellow', 'candy apple red',
              'candy pink', 'capri', 'caput mortuum', 'caramel', 'cardinal', 'caribbean green', 'carmine',
              'carmine (m&p)',
              'carmine pink', 'carmine red', 'carnation pink', 'carnelian', 'carolina blue', 'carrot orange',
              'castleton green', 'catalina blue', 'catawba', 'cedar chest', 'ceil', 'celadon', 'celadon blue',
              'celadon green', 'celeste', 'celestial blue', 'celtic blue', 'cerise', 'cerise pink', 'cerulean',
              'cerulean blue', 'cetacean blue', 'cerulean frost', 'cerulean (crayola)', 'cg blue', 'cg red',
              'chambray', 'chamoisee', 'champagne', 'champagne pink', 'charcoal', 'charleston green', 'charm',
              'charm pink', 'chartreuse (traditional)', 'chartreuse (web)', 'cheese', 'cherry', 'cherry blossom pink',
              'chestnut', 'china pink', 'china rose', 'chinese black', 'chinese blue', 'chinese bronze',
              'chinese brown',
              'chinese green', 'chinese gold', 'chinese orange', 'chinese pink', 'chinese purple', 'chinese red',
              'chinese red', 'chinese silver', 'chinese violet', 'chinese white', 'chinese yellow', 'chlorophyll green',
              'chocolate brown', 'chocolate cosmos', 'chocolate kisses', 'chocolate (traditional)', 'chocolate (web)',
              'christmas blue', 'christmas blue', 'christmas brown', 'christmas brown', 'christmas green',
              'christmas green', 'christmas gold', 'christmas orange', 'christmas orange', 'christmas pink',
              'christmas pink', 'christmas purple', 'christmas purple', 'christmas red', 'christmas red',
              'christmas silver', 'christmas yellow', 'christmas yellow', 'chrome yellow', 'cinereous',
              'cinnabar', 'cinnamon', 'cinnamon satin', 'citrine', 'citrine brown', 'citron', 'claret',
              'classic rose', 'cobalt blue', 'cocoa brown', 'coconut', 'coffee', 'cola', 'columbia blue',
              'conditioner', 'congo pink', 'cool black', 'cool grey', 'cookies and cream', 'copper', 'copper (crayola)',
              'copper penny', 'copper red', 'copper rose', 'coquelicot', 'coral', 'coral pink', 'coral red',
              'coral reef',
              'coral reef (valspar paint color)', 'cordovan', 'corn', 'cornell red', 'cornflower blue', 'cornflower',
              'cornsilk', 'cosmic cobalt', 'cosmic latte', 'coyote brown', 'cotton candy', 'cream', 'crimson',
              'crimson (ua)', 'crimson glory', 'crimson red', 'cultured', 'cyan', 'cyan azure', 'cyan-blue azure',
              'cyan cobalt blue', 'cyan cornflower blue', 'cyan (process)', 'cyber grape', 'cyber yellow', 'cyclamen',
              'daffodil', 'dandelion', 'dandelion (crayola)', 'dark blue', 'dark blue-gray', 'dark bronze',
              'dark bronze (coin)', 'dark brown', 'dark brown-tangelo', 'dark byzantium', 'dark candy apple red',
              'dark cerulean', 'dark charcoal', 'dark chestnut', 'dark chocolate', "dark chocolate (hershey's)",
              'dark cornflower blue', 'dark coral', 'dark cyan', 'dark electric blue', 'dark gold', 'dark goldenrod',
              'dark gray (x11)', 'dark green', 'dark green (x11)', 'dark gunmetal', 'dark imperial blue',
              'dark imperial blue', 'dark jungle green', 'dark khaki', 'dark lava', 'dark lavender',
              'dark lemon lime', 'dark liver', 'dark liver (horses)', 'dark magenta', 'dark medium gray',
              'dark midnight blue', 'dark moss green', 'dark olive green', 'dark orange', 'dark orchid',
              'dark pastel blue', 'dark pastel green', 'dark pastel purple', 'dark pastel red', 'dark pink',
              'dark powder blue', 'dark puce', 'dark purple', 'dark raspberry', 'dark red', 'dark salmon',
              'dark scarlet', 'dark sea green', 'dark sienna', 'dark silver', 'dark sky blue', 'dark slate blue',
              'dark slate gray', 'dark spring green', 'dark tan', 'dark tangerine', 'dark taupe', 'dark terra cotta',
              'dark turquoise', 'dark vanilla', 'dark violet', 'dark yellow', 'dartmouth green', "davy's grey",
              'debian red', 'deep amethyst', 'deep aquamarine', 'deep carmine', 'deep carmine pink',
              'deep carrot orange', 'deep cerise', 'deep champagne', 'deep chestnut', 'deep coffee', 'deep fuchsia',
              'deep green', 'deep green-cyan turquoise', 'deep jungle green', 'deep koamaru', 'deep lemon',
              'deep lilac', 'deep magenta', 'deep maroon', 'deep mauve', 'deep moss green', 'deep peach', 'deep pink',
              'deep puce', 'deep red', 'deep ruby', 'deep saffron', 'deep sky blue', 'deep space sparkle',
              'deep spring bud',
              'deep taupe', 'deep tuscan red', 'deep violet', 'deer', 'denim', 'denim blue', 'desaturated cyan',
              'desert',
              'desert sand', 'desire', 'diamond', 'dim gray', 'dingy dungeon', 'dirt', 'dirty brown',
              'dirty white', 'dodger blue', 'dodie yellow', 'dogwood rose', 'dollar bill', 'dolphin gray',
              'donkey brown', 'drab', 'duke blue', 'dust storm', 'dutch white', 'earthtone', 'earth yellow',
              'ebony', 'ecru', 'eerie black', 'eggplant', 'eggshell', 'egyptian blue', 'electric blue',
              'electric brown', 'electric crimson', 'electric cyan', 'electric green', 'electric indigo',
              'electric lavender', 'electric lime', 'electric orange', 'electric pink', 'electric purple',
              'electric red', 'electric ultramarine', 'electric violet', 'electric yellow', 'emerald',
              'emerald green', 'eminence', 'english green', 'english lavender', 'english red', 'english vermillion',
              'english violet', 'eton blue', 'eucalyptus', 'facebook blue', 'fallow', 'falu red', 'fandango',
              'fandango pink', 'fashion fuchsia', 'fawn', 'feldgrau', 'feldspar', 'fern green', 'ferrari red',
              'field drab', 'fiery rose', 'firebrick', 'fire engine red', 'fire opal', 'flame', 'flamingo pink',
              'flattery', 'flavescent', 'flax', 'flickr blue', 'flickr pink', 'flirt', 'floral white', 'flower girl',
              'fluorescent blue', 'fluorescent orange', 'fluorescent pink', 'fluorescent yellow', 'folly',
              'forest green (crayola)', 'forest green (traditional)', 'forest green (web)', 'french beige',
              'french bistre', 'french blue', 'french fuchsia', 'french lilac', 'french lime', 'french mauve',
              'french middle red purple', 'french pink', 'french plum', 'french puce', 'french raspberry',
              'french rose', 'french sky blue', 'french violet', 'french wine', 'fresh air', 'frostbite',
              'fuchsia', 'fuchsia (crayola)', 'fuchsia pink', 'fuchsia purple', 'fuchsia rose', 'fulvous',
              'fuzzy wuzzy',
              'gainsboro', 'gamboge', 'gamboge orange (brown)', 'garnet', 'gargoyle gas', 'generic viridian',
              'ghost white',
              "giant's club", 'giants orange', 'gin', 'glaucous', 'glossy grape', 'go green', 'gold', 'gold (metallic)',
              'gold (web) (golden)', 'gold (crayola)', 'gold fusion', 'gold foil', 'golden brown', 'golden poppy',
              'golden yellow', 'goldenrod', 'google chrome red', 'google chrome blue', 'google chrome green',
              'google chrome yellow', 'granite gray', 'granny smith apple', 'grape', 'gray (html/css gray)',
              'gray (x11 gray)', 'gray-asparagus', 'gray-blue', 'green', 'green (color wheel) (x11 green)',
              'green (crayola)', 'green (html/css color)', 'green (munsell)', 'green (ncs)', 'green (pantone)',
              'green (pigment)', 'green (ryb)', 'green-blue', 'green-blue (crayola)', 'green cola', 'green-cyan',
              'green lizard', 'green sheen', 'green slime', 'green-yellow', 'green-yellow (crayola)', 'grullo',
              'guppie green', 'gunmetal', 'guyabano', 'halayfabe', 'halloween orange', 'han blue', 'han purple',
              'hansa yellow', 'harlequin', 'harlequin green', 'harmonious rose', 'harvard crimson', 'harvest gold',
              'heart gold', 'heat wave', 'heidelberg red', 'heliotrope', 'heliotrope gray', 'heliotrope magenta',
              'hollywood cerise', 'honeydew', 'honolulu blue', "hooker's green", 'hot magenta', 'hot pink',
              'hunter green', 'iceberg', 'iced tea', 'icterine', 'iguana green', 'illuminating emerald', 'imperial',
              'imperial blue', 'imperial purple', 'imperial red', 'inchworm', 'independence', 'india green',
              'indian red',
              'indian yellow', 'indigo', 'indigo dye', 'indigo (crayola)', 'indigo (rainbow)', 'indigo (web)',
              'infra red',
              'interdimensional blue', 'international klein blue', 'international orange (aerospace)',
              'international orange (engineering)', 'international orange (golden gate bridge)', 'iris', 'iron',
              'irresistible', 'isabelline', 'italian sky blue', 'ivory', 'jacarta', 'jacko bean', 'jade',
              'japanese carmine',
              'japanese indigo', 'japanese laurel', 'japanese violet', 'jasmine', 'jasper', 'jasper orange',
              'jazzberry jam',
              'jelly bean', 'jelly bean blue', 'jet', 'jet stream', 'jonquil', 'jordy blue', 'june bud', 'jungle green',
              'kelly green', 'kenyan copper', 'keppel', 'key lime', 'khaki (html/css) (khaki)',
              'khaki (x11) (light khaki)',
              'kiwi', 'kobe', 'kobi', 'kobicha', 'kombu green', 'ksu purple', 'ku crimson', 'la salle green',
              'languid lavender', 'lanzones', 'lapis lazuli', 'laser lemon', 'laurel green', 'lava',
              'lavender (floral)',
              'lavender (web)', 'lavender blue', 'lavender blush', 'lavender gray', 'lavender indigo',
              'lavender magenta',
              'lavender mist', 'lavender pink', 'lavender purple', 'lavender rose', 'lawn green', 'lemon',
              'lemon chiffon',
              'lemon curry', 'lemon glacier', 'lemon iced tea', 'lemon lime', 'lemon lime', 'lemon meringue',
              'lemon yellow',
              'lemon yellow (crayola)', 'lenurple', 'liberty', 'licorice', 'light apricot', 'light blue', 'light brown',
              'light carmine pink', 'light chocolate cosmos', 'light cobalt blue', 'light coral',
              'light cornflower blue',
              'light crimson', 'light cyan', 'light deep pink', 'light french beige', 'light fuchsia pink',
              'light gold',
              'light goldenrod', 'light goldenrod yellow', 'light gray', 'light grayish magenta', 'light green',
              'light hot pink', 'light khaki', 'light medium orchid', 'light moss green', 'light mustard',
              'light orange',
              'light orchid', 'light pastel purple', 'light periwinkle', 'light pink', 'light red', 'light red ochre',
              'light salmon', 'light salmon pink', 'light sea green', 'light silver', 'light sky blue',
              'light slate gray',
              'light steel blue', 'light taupe', 'light thulian pink', 'light turquoise', 'light violet',
              'light yellow',
              'lilac', 'lilac luster', 'lime (color wheel)', 'lime (web) (x11 green)', 'lime green', 'limerick',
              'lincoln green', 'linen', 'lion', 'liseran purple', 'little boy blue', 'little girl pink', 'liver',
              'liver (dogs)', 'liver (organ)', 'liver chestnut', 'livid', 'lotion', 'lotion blue', 'lotion pink',
              'lumber', 'lust', 'maastricht blue', 'macaroni and cheese', 'madder lake', 'magenta', 'mahogany',
              'maize', 'maize (crayola)', 'majorelle blue', 'malachite', 'manatee', 'mandarin', 'mango', 'mango green',
              'mango tango', 'mantis', 'mardi gras', 'marigold', 'maroon (crayola)', 'maroon (html/css)',
              'maroon (x11)',
              'mauve', 'mauve taupe', 'mauvelous', 'maximum blue', 'maximum blue green', 'maximum blue purple',
              'maximum green', 'maximum green yellow', 'maximum orange', 'maximum purple', 'maximum pink',
              'maximum red',
              'maximum red purple', 'maximum violet', 'maximum yellow', 'maximum yellow red', 'may green', 'maya blue',
              'meat brown', 'medium aquamarine', 'medium blue', 'medium candy apple red', 'medium carmine',
              'medium champagne', 'medium electric blue', 'medium green', 'medium jungle green',
              'medium lavender magenta',
              'medium orange', 'medium orchid', 'medium persian blue', 'medium pink', 'medium purple', 'medium red',
              'medium red-violet', 'medium ruby', 'medium sea green', 'medium sky blue', 'medium slate blue',
              'medium spring bud', 'medium spring green', 'medium taupe', 'medium turquoise', 'medium tuscan red',
              'medium vermilion', 'medium violet', 'medium violet-red', 'medium yellow', 'mellow apricot',
              'mellow yellow',
              'melon', 'melon (crayola)', 'menthol', 'metallic blue', 'metallic bronze', 'metallic brown',
              'metallic gold',
              'metallic green', 'metallic orange', 'metallic pink', 'metallic red', 'metallic seaweed',
              'metallic silver', 'metallic sunburst', 'metallic violet', 'metallic yellow', 'mexican pink',
              'microsoft blue', 'microsoft edge blue', 'microsoft green', 'microsoft red', 'microsoft yellow',
              'middle blue', 'middle blue green', 'middle blue purple', 'middle grey', 'middle green',
              'middle green yellow', 'middle purple', 'middle red', 'middle red purple', 'middle yellow',
              'middle yellow red', 'midnight', 'midnight blue', 'midnight blue', 'midnight green (eagle green)',
              'mikado yellow', 'milk', 'milk chocolate', 'mimi pink', 'mindaro', 'ming', 'minion yellow', 'mint',
              'mint cream', 'mint green', 'misty moss', 'misty rose', 'moccasin', 'mocha', 'mode beige', 'moonstone',
              'moonstone blue', 'mordant red 19', 'morning blue', 'moss green', 'mountain meadow', 'mountbatten pink',
              'msu green', 'mud', 'mughal green', 'mulberry', 'mulberry (crayola)', "mummy's tomb", 'mustard',
              'mustard brown', 'mustard green', 'mustard yellow', 'myrtle green', 'mystic', 'mystic maroon',
              'mystic red', 'nadeshiko pink', 'napier green', 'naples yellow', 'navajo white', 'navy blue',
              'navy blue (crayola)', 'navy purple', 'neon blue', 'neon brown', 'neon carrot', 'neon cyan',
              'neon fuchsia', 'neon gold', 'neon gray', 'neon dark green', 'neon green', 'neon green', 'neon pink',
              'neon purple', 'neon red', 'neon scarlet', 'neon silver', 'neon tangerine', 'neon yellow', 'new car',
              'new york pink', 'nickel', 'nintendo red', 'non-photo blue', 'nyanza', 'ocean blue', 'ocean boat blue',
              'ocean green', 'ochre', 'office green', 'ogre odor', 'old burgundy', 'old gold', 'old heliotrope',
              'old lace', 'old lavender', 'old mauve', 'old moss green', 'old rose', 'old silver', 'olive',
              'olive drab (#3)', 'olive drab #7', 'olive green', 'olivine', 'onyx', 'opal', 'opera mauve', 'orange',
              'orange (color wheel)', 'orange (crayola)', 'orange (pantone)', 'orange (ryb)', 'orange (web)',
              'orange iced tea', 'orange peel', 'orange-red', 'orange-red (crayola)', 'orange soda', 'orange soda',
              'orange-yellow', 'orange-yellow (crayola)', 'orchid', 'orchid pink', 'orchid (crayola)', 'orioles orange',
              'otter brown', 'outer space', 'outer space (crayola)', 'outrageous orange', 'oxblood', 'oxford blue',
              'oxley', 'ou crimson red', 'pacific blue', 'pakistan green', 'palatinate blue', 'palatinate purple',
              'pale aqua', 'pale blue', 'pale brown', 'pale carmine', 'pale cerulean', 'pale chestnut', 'pale copper',
              'pale cornflower blue', 'pale cyan', 'pale gold', 'pale goldenrod', 'pale green', 'pale lavender',
              'pale magenta', 'pale magenta-pink', 'pale pink', 'pale plum', 'pale red-violet', 'pale robin egg blue',
              'pale silver', 'pale spring bud', 'pale taupe', 'pale turquoise', 'pale violet', 'pale violet-red',
              'palm leaf', 'pansy purple', 'paolo veronese green', 'papaya whip', 'paradise pink', 'paris green',
              'parrot pink', 'pastel blue', 'pastel brown', 'pastel gray', 'pastel green', 'pastel magenta',
              'pastel orange', 'pastel pink', 'pastel purple', 'pastel red', 'pastel violet', 'pastel yellow',
              'patriarch', "payne's grey", 'peach', 'peach (crayola)', 'peach-orange', 'peach puff', 'peach-yellow',
              'pear', 'pearl', 'pearl aqua', 'pearly purple', 'peridot', 'periwinkle', 'periwinkle (crayola)',
              'permanent geranium lake', 'persian blue', 'persian green', 'persian indigo', 'persian orange',
              'persian pink', 'persian plum', 'persian red', 'persian rose', 'persimmon', 'peru', 'pewter blue',
              'philippine blue', 'philippine bronze', 'philippine brown', 'philippine gold', 'philippine golden yellow',
              'philippine gray', 'philippine green', 'philippine indigo', 'philippine orange', 'philippine pink',
              'philippine red', 'philippine silver', 'philippine sky blue', 'philippine violet', 'philippine yellow',
              'phlox', 'phthalo blue', 'phthalo green', 'picton blue', 'pictorial carmine', 'piggy pink', 'pine green',
              'pine tree', 'pineapple', 'pink', 'pink (pantone)', 'pink diamond (ace hardware color)',
              'pink diamond (independent retailers colors)', 'pink flamingo', 'pink lace', 'pink lavender',
              'pink-orange', 'pink pearl', 'pink raspberry', 'pink sherbet', 'pistachio', 'pixie powder', 'platinum',
              'plum', 'plum (web)', 'plump purple', 'police blue', 'polished pine', 'pomp and power', 'popstar',
              'portland orange', 'powder blue', 'prilly blue', 'prilly pink', 'prilly red', 'princess perfume',
              'princeton orange', 'prune', 'prussian blue', 'psychedelic purple', 'puce', 'puce red',
              'pullman brown (ups brown)', 'pullman green', 'pumpkin', 'purple (html)', 'purple (munsell)',
              'purple (x11)', 'purple heart', 'purple mountain majesty', 'purple navy', 'purple pizzazz', 'purple plum',
              'purple taupe', 'purpureus', 'quartz', 'queen blue', 'queen pink', 'quick silver', 'quinacridone magenta',
              'quincy', 'rackley', 'radical red', 'raisin black', 'rajah', 'raspberry', 'raspberry glace',
              'raspberry pink', 'raspberry rose', 'raw sienna', 'raw umber', 'razzle dazzle rose', 'razzmatazz',
              'razzmic berry', 'rebecca purple', 'red', 'red (crayola)', 'red (munsell)', 'red (ncs)', 'red (pantone)',
              'red (pigment)', 'red (ryb)', 'red-brown', 'red cola', 'red devil', 'red-orange', 'red-orange (crayola)',
              'red-orange (color wheel)', 'red-purple', 'red rum', 'red salsa', 'red strawberry', 'red-violet',
              'red-violet (crayola)', 'red-violet (color wheel)', 'redwood', 'registration black', 'resolution blue',
              'rhythm', 'rich brilliant lavender', 'rich carmine', 'rich electric blue', 'rich lavender', 'rich lilac',
              'rich maroon', 'rifle green', 'ripe mango', 'roast coffee', 'robin egg blue', 'rocket metallic',
              'roman silver', 'root beer', 'rose', 'rose bonbon', 'rose dust', 'rose ebony', 'rose garnet', 'rose gold',
              'rose madder', 'rose pink', 'rose quartz', 'rose quartz pink', 'rose red', 'rose taupe', 'rose vale',
              'rosewood', 'rosy brown', 'royal azure', 'royal blue', 'royal blue', 'royal brown', 'royal fuchsia',
              'royal green', 'royal orange', 'royal pink', 'royal red', 'royal red', 'royal purple', 'royal yellow',
              'ruber', 'rubine red', 'ruby', 'ruby red', 'rufous', 'rum', 'russet', 'russian green', 'russian violet',
              'rust', 'rusty red', 'sacramento state green', 'saddle brown', 'safety orange',
              'safety orange (blaze orange)', 'safety yellow', 'saffron', 'sage', "st. patrick's blue", 'salem',
              'salmon', 'salmon rose', 'salmon pink', 'samsung blue', 'sand', 'sand dune', 'sandstorm', 'sandy brown',
              'sandy tan', 'sandy taupe', 'sap green', 'sapphire', 'sapphire blue', 'sasquatch socks',
              'satin sheen gold', 'scarlet', 'scarlet', 'schauss pink', 'school bus yellow', "screamin' green",
              'sea blue', 'sea foam green', 'sea green', 'sea green (crayola)', 'sea serpent', 'seal brown', 'seashell',
              'selective yellow', 'sepia', 'shadow', 'shadow blue', 'shampoo', 'shamrock green', 'shandy',
              'sheen green', 'shimmering blush', 'shiny shamrock', 'shocking pink', 'shocking pink (crayola)', 'sienna',
              'silver', 'silver (crayola)', 'silver (metallic)', 'silver chalice', 'silver foil', 'silver lake blue',
              'silver pink', 'silver sand', 'sinopia', 'sizzling red', 'sizzling sunrise', 'skobeloff', 'sky blue',
              'sky blue (crayola)', 'sky magenta', 'slate blue', 'slate gray', 'slimy green',
              'smalt (dark powder blue)', 'smashed pumpkin', 'smitten', 'smoke', 'smokey topaz', 'smoky black', 'snow',
              'soap', 'solid pink', 'sonic silver', 'spartan crimson', 'space cadet', 'spanish bistre', 'spanish blue',
              'spanish carmine', 'spanish crimson', 'spanish gray', 'spanish green', 'spanish orange', 'spanish pink',
              'spanish purple', 'spanish red', 'spanish sky blue', 'spanish violet', 'spanish viridian',
              'spanish yellow', 'spicy mix', 'spiro disco ball', 'spring bud', 'spring frost', 'spring green',
              'spring green (crayola)', 'star command blue', 'steel blue', 'steel pink', 'steel teal',
              'stil de grain yellow', 'straw', 'strawberry', 'stop red', 'strawberry iced tea', 'strawberry red',
              'sugar plum', 'sunburnt cyclops', 'sunglow', 'sunny', 'sunray', 'sunset', 'sunset orange', 'super pink',
              'sweet brown', 'tan', 'tan (crayola)', 'tangelo', 'tangerine', 'tangerine yellow', 'tango pink',
              'tart orange', 'taupe', 'taupe gray', 'tea green', 'tea rose', 'tea rose', 'teal', 'teal blue',
              'teal deer', 'teal green', 'telemagenta', 'temptress', 'tenné (tawny)', 'terra cotta', 'thistle',
              'thistle (crayola)', 'thulian pink', 'tickle me pink', 'tiffany blue', "tiger's eye", 'timberwolf',
              'titanium', 'titanium yellow', 'tomato', 'tomato sauce', 'toolbox', 'tooth', 'topaz', 'tractor red',
              'trolley grey', 'tropical rain forest', 'tropical violet', 'true blue', 'tufts blue', 'tulip',
              'tumbleweed', 'turkish rose', 'turquoise', 'turquoise blue', 'turquoise green', 'turquoise surf',
              'turtle green', 'tuscan', 'tuscan brown', 'tuscan red', 'tuscan tan', 'tuscany', 'twilight lavender',
              'twitter blue', 'tyrian purple', 'ultramarine', 'ultramarine blue', "ultramarine blue (caran d'ache)",
              'ultra pink', 'ultra red', 'umber', 'unbleached silk', 'united nations blue', 'unmellow yellow',
              'up maroon', 'upsdell red', 'urobilin', 'vampire black', 'van dyke brown', 'vanilla', 'vanilla ice',
              'vegas gold', 'venetian red', 'verdigris', 'vermilion', 'vermilion', 'veronica', 'verse green',
              'very light azure', 'very light blue', 'very light malachite green', 'very light tangelo',
              'very pale orange', 'very pale yellow', 'vine green', 'violet', "violet (caran d'ache)",
              'violet (color wheel)', 'violet (crayola)', 'violet (ryb)', 'violet (web)', 'violet-blue',
              'violet-blue (crayola)', 'violet-red', 'violin brown', 'viridian', 'viridian green', 'vista blue',
              'vivid amber', 'vivid auburn', 'vivid burgundy', 'vivid cerise', 'vivid cerulean', 'vivid crimson',
              'vivid gamboge', 'vivid lime green', 'vivid malachite', 'vivid mulberry', 'vivid orange',
              'vivid orange peel', 'vivid orchid', 'vivid raspberry', 'vivid red', 'vivid red-tangelo',
              'vivid sky blue', 'vivid tangelo', 'vivid tangerine', 'vivid vermilion', 'vivid violet', 'vivid yellow',
              'water', 'watermelon', 'watermelon red', 'watermelon yellow', 'waterspout', 'weldon blue', 'wenge',
              'wheat', 'white', 'white chocolate', 'white coffee', 'white smoke', 'wild orchid', 'wild strawberry',
              'wild watermelon', 'willpower orange', 'windsor tan', 'wine', 'wine dregs', 'wine red', 'winter sky',
              'winter wizard', 'wintergreen dream', 'wisteria', 'wood brown', 'xanadu', 'yellow', 'yellow (crayola)',
              'yellow (munsell)', 'yellow (ncs)', 'yellow (pantone)', 'yellow (process)', 'yellow (ryb)',
              'yellow-green', 'yellow-green (crayola)', 'yellow orange', 'yellow orange', 'yellow rose',
              'yellow sunshine', 'yinmn blue', 'zaffre', 'zebra white', 'zinnwaldite']
